name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system packages
      run: |
        sudo apt update
        sudo apt install -y openjdk-17-jdk zip unzip wget

    - name: Install Python tooling
      run: |
        pip install --upgrade pip
        pip install buildozer cython

    - name: Prepare Android config folder
      run: |
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        
    - name: Clear Buildozer cache
      run: |
        rm -rf ~/.buildozer

    - name: Install Android Build Tools 33.0.2
      run: |
        export ANDROID_SDK_ROOT=/usr/local/lib/android/sdk
        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH

        yes | sdkmanager --licenses || true
        sdkmanager "build-tools;33.0.2" "platform-tools" "platforms;android-33"

        ls -la $ANDROID_SDK_ROOT/build-tools



    - name: Build APK
      env:
        ANDROID_HOME: /usr/local/lib/android/sdk
        ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
        ANDROID_BUILD_TOOLS_VERSION: "33.0.2"
        PIP_USER: "no"
        PYTHONNOUSERSITE: "0"
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: BlackExcellenceAPK
        path: bin/*.apk
